# Generated by Django 3.2 on 2023-08-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram_editor', '0002_auto_20230801_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinformationschema',
            name='linked',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram_editor.informationschema'),
        ),
        migrations.AddField(
            model_name='informationschema',
            name='linked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagram_editor.informationschema'),
        ),
    ]
