# Generated by Django 3.2 on 2023-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram_editor', '0003_auto_20230801_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinformationschema',
            name='linked',
        ),
        migrations.RemoveField(
            model_name='informationschema',
            name='linked',
        ),
        migrations.AddField(
            model_name='informationschema',
            name='linked',
            field=models.ManyToManyField(blank=True, null=True, related_name='_diagram_editor_informationschema_linked_+', to='diagram_editor.InformationSchema', verbose_name='Связана с:'),
        ),
    ]
