# Generated by Django 3.2 on 2023-08-01 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagram_editor', '0004_auto_20230801_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinformationschema',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='informationschema',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationschema',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='_diagram_editor_informationschema_linked_+', to='diagram_editor.InformationSchema', verbose_name='Связана с:'),
        ),
    ]
