# Generated by Django 3.2 on 2023-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diagram_editor', '0005_auto_20230801_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationschema',
            name='permitted_groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='Доступна для:'),
        ),
    ]
