# Generated by Django 3.2 on 2023-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportfragment_report_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfragment',
            name='report_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Название фрагмента'),
            preserve_default=False,
        ),
    ]
