# Generated by Django 3.2 on 2023-08-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reportfragment_report_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfragment',
            options={'ordering': ('report_order',), 'verbose_name': 'Фрагмент отчета', 'verbose_name_plural': 'Фрагменты отчетов'},
        ),
    ]
